"""Registry repository contracts (Protocols).

Pure interfaces, zero infrastructure imports -- same pattern as
core/contracts/repositories.py. These are what the four registry service
classes in core/registry/ depend on; infrastructure/persistence provides
the Postgres-backed implementations.

Each registry is a catalog only (Router/Provider/Tool/Resource Contract
invariant: "Tool existence does not grant permission" -- registries record
what *exists* and what *depends on what*, never execute anything).
"""
from __future__ import annotations

from typing import Optional, Protocol

from core.registry.capability_registry import Capability
from core.registry.model_registry import Model
from core.registry.provider_registry import Provider
from core.registry.resource_registry import Resource
from core.registry.tool_registry import ToolDefinition


class CapabilityRepository(Protocol):
    def create(self, capability: Capability) -> None: ...
    def get(self, capability_id: str) -> Optional[Capability]: ...
    def update(self, capability: Capability) -> None: ...
    def delete(self, capability_id: str) -> None: ...
    def list_all(self) -> list[Capability]: ...


class ProviderRepository(Protocol):
    def create(self, provider: Provider) -> None: ...
    def get(self, provider_id: str) -> Optional[Provider]: ...
    def update(self, provider: Provider) -> None: ...
    def delete(self, provider_id: str) -> None: ...
    def list_all(self) -> list[Provider]: ...


class ResourceRepository(Protocol):
    def create(self, resource: Resource) -> None: ...
    def get(self, resource_id: str) -> Optional[Resource]: ...
    def update(self, resource: Resource) -> None: ...
    def delete(self, resource_id: str) -> None: ...
    def list_all(self) -> list[Resource]: ...


class ToolDefinitionRepository(Protocol):
    def create(self, tool: ToolDefinition) -> None: ...
    def get(self, tool_id: str) -> Optional[ToolDefinition]: ...
    def update(self, tool: ToolDefinition) -> None: ...
    def delete(self, tool_id: str) -> None: ...
    def list_all(self) -> list[ToolDefinition]: ...


class ModelRepository(Protocol):
    def create(self, model: Model) -> None: ...
    def get(self, model_id: str) -> Optional[Model]: ...
    def update(self, model: Model) -> None: ...
    def delete(self, model_id: str) -> None: ...
    def list_all(self) -> list[Model]: ...
    def list_for_provider(self, provider_id: str) -> list[Model]: ...
