"""Repository contracts (Protocols) for the Core / Control Plane domain.

These are pure interfaces: no SQLAlchemy, no psycopg2, no infrastructure
imports of any kind. Infrastructure implementations (e.g. Postgres) live in
src/infrastructure/persistence and must satisfy these Protocols structurally.

This is the boundary Claude B's Model Gateway / tool system will depend on
without needing to know the persistence technology (Bible
02_ARCHITECTURE/02_DEPENDENCY_DIRECTION.md: core never imports infra).
"""
from __future__ import annotations

from typing import Optional, Protocol

from core.domain.agent import Agent
from core.domain.checkpoint import Checkpoint
from core.domain.event import Event
from core.domain.session import Session
from core.domain.task import Task
from core.domain.turn import Turn


class TaskRepository(Protocol):
    def create(self, task: Task) -> None: ...
    def get(self, task_id: str) -> Optional[Task]: ...
    def update(self, task: Task) -> None: ...
    def list_children(self, parent_task_id: str) -> list[Task]: ...


class AgentRepository(Protocol):
    def create(self, agent: Agent) -> None: ...
    def get(self, agent_id: str) -> Optional[Agent]: ...
    def update(self, agent: Agent) -> None: ...
    def list_for_task(self, task_id: str) -> list[Agent]: ...


class SessionRepository(Protocol):
    def create(self, session: Session) -> None: ...
    def get(self, session_id: str) -> Optional[Session]: ...
    def update(self, session: Session) -> None: ...
    def list_for_task(self, task_id: str) -> list[Session]: ...


class TurnRepository(Protocol):
    def create(self, turn: Turn) -> None: ...
    def get(self, turn_id: str) -> Optional[Turn]: ...
    def update(self, turn: Turn) -> None: ...
    def list_for_session(self, session_id: str) -> list[Turn]:
        """Must return turns ordered by sequence_number ascending
        (SESSION_CONTRACT.md invariant #2: turns are ordered within a
        session)."""
        ...


class EventRepository(Protocol):
    def append(self, event: Event) -> None:
        """Append-only. There is deliberately no update/delete method:
        events are immutable records (06_CORE_DOMAIN_MODEL.md)."""
        ...

    def get(self, event_id: str) -> Optional[Event]: ...
    def list_for_task(self, task_id: str) -> list[Event]:
        """Must return events ordered by timestamp ascending."""
        ...


class CheckpointRepository(Protocol):
    def create(self, checkpoint: Checkpoint) -> None: ...
    def get(self, checkpoint_id: str) -> Optional[Checkpoint]: ...
    def list_for_task(self, task_id: str) -> list[Checkpoint]: ...
    def latest_for_task(self, task_id: str) -> Optional[Checkpoint]: ...
